#!/bin/sh
# Generated automatically from adapack-config.in by configure.

prefix=/usr/local
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib

gtkada_libs=`gtkada-config`
gtkada_cflags="-I/usr/local/include/gtkada"
adapack_libs="-L$includedir/adapack -L$libdir"
adapack_cflags="-I$includedir/adapack"
adapack_lflags="-ladapack"
opengl_lflags=" -lGL -lXi -lXmu -lglut"

usage()
{
        cat <<EOF
Usage: adapack-config [OPTIONS]
Options:
        [--prefix]
        [--version|-v]
        [--libs]
        [--cflags]
        [--help|-h]
EOF
        exit $1
}

# Can have the following values:
#   0 = none
#   1 = cflags
#   2 = libs
#   4 = complete
output_type=4
modules=""

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --help|-h)
      usage 1>&2
      exit 1
      ;;
    --prefix)
      echo $prefix
      output_type=0
      ;;
    --version|-v)
      echo 1.0.2
      exit 1
      ;;
    --libs)
      output_type=2
      ;;
    --cflags)
      output_type=1
      ;;
    *)
      usage 1>&2
      exit 1
      ;;
  esac
  shift
done

case $output_type in
   1) echo $adapack_cflags $gtkada_cflags ;;
   2) echo $adapack_libs $adapack_lflags $gtkada_libs $opengl_lflags ;;
   4) echo $adapack_cflags $gtkada_cflags -largs $adapack_libs $adapack_lflags $gtkada_libs $opengl_lflags ;;
esac
