#!/bin/bash

if [ "$1" == "-a" ]
then
  # Update the whole disks, but with the informations of the last updatedb
  locate -r "/\(\.git\|\.svn\)$"
  c=X
  locate -r "/CVS$" \
  | grep -va "^/main/cvsd/" \
  | while read f
    do
      a=$(dirname "$f")
      if ! echo "$a" | grep -q "$c"
      then
        echo "$a"
        c="$a"
      fi
    done
else
  # Update only the local directory and subdirectories
  find . -xdev -type d -name ".git" -or -name ".svn"
fi \
| grep -avw "old" \
| sed "s;/\.\(git\|svn\)$;;g" \
| sort -u \
| while read f
  do
    pushd "$f" > /dev/null 2>&1
    update
    popd > /dev/null 2>&1
    echo
  done

exit 0
