#!/bin/bash

. $(dirname "$0")/library.sh

LIST=$(if [ "$1" == "-a" ]
       then
         # Update the whole disks, but with the informations of the last updatedb
         locate -r "/\(\.git\|\.svn\|/CVS\)$" \
         | grep -va "^/main/cvsd/" \
         | sed "s:/CVS$::"
       else
         # Update only the local directory and subdirectories
         find . -xdev -type d -name ".git" -or -name ".svn" -or -name "CVS" \
         | sed "s:/CVS$::"
       fi
      )

filterSubDirectories "$LIST" \
| grep -avw "old" \
| sed "s;/\.\(git\|svn\)$;;g" \
| sort -u \
| while read f
  do
    pushd "$f" > /dev/null 2>&1
    update
    popd > /dev/null 2>&1
    echo
  done

exit 0
