#!/bin/bash

echo -e "\e[1mFormatting:\e[0m \\\\e[XXm"
echo -e "  \e[1mSet:\e[0m               \e[1mReset:\e[0m"
echo -e "                     0  : \e[0mDefault (all flags reset)\e[0m"
echo -e "  1 : \e[1mBold\e[0m           21 : \e[21mDouble underline\e[0m"
echo -e "  2 : \e[2mDim\e[22m            22 : \e[22mNot Dim\e[0m"
echo -e "  3 : \e[3mItalic\e[23m         23 : \e[23mNot Italic\e[0m"
echo -e "  4 : \e[4mUnderlined\e[24m     24 : \e[24mNot Underlined\e[0m"
echo -e "  5 : \e[5mBlink\e[25m          25 : \e[25mNot Blink\e[0m"
echo -e "  7 : \e[7mInverted\e[27m       27 : \e[27mNot Inverted\e[0m"
echo -e "  8 : \e[8mHidden\e[28m         28 : \e[28mNot Hidden\e[0m"
echo -e "  9 : \e[9mStrikeout\e[29m      29 : \e[29mNot Strikeout\e[0m"
echo
echo -e "\e[1mColors:\e[0m \\\\e[XXm"
echo -e "  \e[1mForeground:\e[0m        \e[1mBackground:\e[0m"
echo -e "  39 : \e[39mDefault\e[0m       49  : \e[49mDefault\e[0m"
echo -e "  30 : \e[30mBlack\e[0m         40  : \e[40mBlack\e[0m"
echo -e "  31 : \e[31mRed\e[0m           41  : \e[41mRed\e[0m"
echo -e "  32 : \e[32mGreen\e[0m         42  : \e[42mGreen\e[0m"
echo -e "  33 : \e[33mYellow\e[0m        43  : \e[43mYellow\e[0m"
echo -e "  34 : \e[34mBlue\e[0m          44  : \e[44mBlue\e[0m"
echo -e "  35 : \e[35mMagenta\e[0m       45  : \e[45mMagenta\e[0m"
echo -e "  36 : \e[36mCyan\e[0m          46  : \e[46mCyan\e[0m"
echo -e "  37 : \e[37mLight gray\e[0m    47  : \e[47mLight gray\e[0m"
echo -e "  90 : \e[90mDark gray\e[0m     100 : \e[100mDark gray\e[0m"
echo -e "  91 : \e[91mLight red\e[0m     101 : \e[101mLight red\e[0m"
echo -e "  92 : \e[92mLight green\e[0m   102 : \e[102mLight green\e[0m"
echo -e "  93 : \e[93mLight yellow\e[0m  103 : \e[103mLight yellow\e[0m"
echo -e "  94 : \e[94mLight blue\e[0m    104 : \e[104mLight blue\e[0m"
echo -e "  95 : \e[95mLight magenta\e[0m 105 : \e[105mLight magenta\e[0m"
echo -e "  96 : \e[96mLight cyan\e[0m    106 : \e[106mLight cyan\e[0m"
echo -e "  97 : \e[97mWhite\e[0m         107 : \e[107mWhite\e[0m"
echo

function printColors() {
  local fgbg=$1
  local start=$2
  local end
  local color
  let end=$2+$3-1
  echo -n "  "
  for color in $(seq $start $end)
  do
    printf "\e[${fgbg};5;%sm %3s \e[0m" $color $color
  done
}

echo -e "\e[1mColor map:\e[0m"
echo -e "  \e[1mBase colors:\e[0m"
echo -en "    \e[1mForeground: \\\\e[38;5;\e[7m0-15\e[0mm\e[0m\n  "
printColors 38 0 16
echo
echo -en "    \e[1mBackground: \\\\e[48;5;\e[7m0-15\e[0mm\e[0m\n  "
printColors 48 0 16
echo
echo
echo -e "  \e[1mGray shades:\e[0m"
echo -en "    \e[1mForeground: \\\\e[38;5;\e[7m232-255\e[0mm\e[0m\n  "
printColors 38 232 24
echo
echo -en "    \e[1mBackground: \\\\e[48;5;\e[7m232-255\e[0mm\e[0m\n  "
printColors 48 232 24
echo
echo
echo -e "      \e[1mForeground: \\\\e[38;5;\e[7m16-231\e[0mm\e[0m     \e[1mBackground: \\\\e[48;5;\e[7m16-231\e[0mm\e[0m"
printf "        0    1    2    3    4    5      0    1    2    3    4    5\n"
for base in $(seq 16 6 231)
do
  printf "  %2d" $[ (base-16)/6 ]
  printColors 38 $base 6
  printColors 48 $base 6
echo
done
