#!/bin/bash

declare -a b=(0 0 0)
declare -i d=0

while read x
do
  a=($x)
  if [ "${a[0]}" == "$b" ]
  then
    if [ $d == 0 ]
    then
      echo "$c"
    fi
    echo "$x"
    d=1
  else
    if [ $d != 0 ]
    then
      echo
      d=0
    fi
  fi
  b=${a[0]}
  c=$x
done < $1 | sed "s/^[0-9a-f]*  *\(.*\)/\"\1\"/g"
