#!/bin/bash

hostname="$1"
username="$2"
database="$3"
filename="$4"

if [ -z "$filename" ]
then
cat <<!
Usage: $0 <hostname> <username> <database> <filename>

Where filename is an apt file generated by the tests.
!
  exit -1
fi

if [ ! -f "$filename" ]
then
  echo "File not found: $filename"
  exit -1
fi

(
  echo -e "delete from scma_calculation;\ninsert into scma_calculation (id, changed, formula) values"
  grep -A 999999 "^+----" "$filename" \
  | sed "s/^+----.*//;s/);$/)/;s/^insert into scma_calculation (id, changed, formula) values /,/" \
  | sed "s/^,(1,/(1,/" \
  | grep -v "^ *$"
  echo ";"
) | psql -h "$hostname" -U "$username" "$database"
