#!/bin/bash

pushd "$1"

if [ -f cddb.inf ]
then
  for x in `\\grep DISCID cddb.inf | \\sed "s/\\(.*\\)=\\(.*\\)/\\2/g" | \\tr "," "\\n" | \\sort | \\uniq`
  do
    export FILE=/opt/kde?/share/apps/kscd/cddb/*/$x

    if [ "$FILE" != "" -a -f "$FILE" ]
    then
      \echo copy to $FILE
      \cp cddb.inf $FILE
    else
      \echo copy to /opt/kde?/share/apps/kscd/cddb/misc/$x
      \cp cddb.inf /opt/kde?/share/apps/kscd/cddb/misc/$x
    fi
  done
fi

popd
