#!/bin/bash

. $(dirname "$0")/library.sh

if ! checkDependencies wmctrl xwininfo
then
  exit -1
fi

LABEL="$1"

if [ -z "$LABEL" ]
then
  echo "Usage: $(basename "$0") <label> [command]"
  exit -1
fi

exec > /tmp/minify.log 2>&1

shift 1

"$@"

LC_ALL=C

i=0
while true
do
  if ${XWININFO} -id $(${WMCTRL} -l | grep -i "$LABEL" | cut -d" " -f1) 2>&1 | grep -q "Map State: IsUnMapped"
  then
    echo "Unmapped"
    break
  fi

  let i=i+1
  ${WMCTRL} -c "$LABEL"

  if [ $? -eq 0 ]
  then
    echo "Success"
    break
  elif [ $i -ge 60 ]
  then
    echo "Timeout"
    break
  else
    echo "Wait 0.25"
    sleep 0.25
  fi
done
