#!/bin/bash

declare -i sz

while [ "$1" != "" ]
do
  sz=`wc -c "$1" | awk '{printf("%s", $1);}'`
  tail -c 128 "$1" | grep TAG > /dev/null
  if [ $? == 1 ]
  then
    md5sum --binary "$1" | awk '{printf("%s", $1);}'
  else
    sz=sz-128
    head --byte=$sz "$1" | md5sum --binary | awk '{printf("%s", $1);}'
  fi
  echo " $sz $1"
  shift
done
