#!/bin/bash

TYPE=$(
       d="$(pwd -P)"

       while true
       do
         if [ -e "$d/.git" ]
         then
           echo "GIT"
           break
         elif [ -e "$d/.svn" ]
         then
           echo "SVN"
           break
         elif [ -e "$d/CVS" ]
         then
           echo "CVS"
           break
         fi

         if [ "$d" == "/" ]
         then
           break
         fi

         d="$(dirname "$d")"
       done
      )

echo -e "\e[38;5;245m############### Checking directory: \e[01;33m$PWD\e[00m"
echo "Found a $TYPE repository. Updating."

case "$TYPE" in
  CVS)
    cvs update -d -P "$@" 2>&1 \
    | grep -v "^cvs update"
    ;;

  SVN)
    svn update "$@"
    ;;

  GIT)
    LC_ALL=en_US.UTF-8 git pull
    ;;

  *)
    echo "Not a recognised project"
    exit -1
esac 2>&1 \
| sed $'s/^.*error.*$/\e[48;5;1m&\e[0m/' \
| sed $'s/^.*up-to-date.*$/\e[92m&\e[0m/' \
| sed $'s/\\(Current branch \\)\\(.*\\)\\( is up to date\\)/\e[92m\\1\e[0m\e[96m\\2\e[0m\e[92m\\3\e[0m/' \
| sed $'s/\\(At revision \\)\\(.*\\)\\./\e[92m\\1\e[0m\e[96m\\2\e[0m\e[92m.\e[0m/'

exit 0
